### PR TITLE
Fix: used the os module to prompt a directory change for accessing the README.md file

### LINKED ISSUE #5: Change setup.py to open README.md file from root directory.
Right now there's a bug in `setup.py` file. 
https://github.com/abhinavsp0730/khronos/blob/a9f09e6a81c89808452917325ded0aff78bb39ab/Khronos/setup.py#L7

So, whenever I have to push a new version to PyPi, I have to manually put `README.md` file to dir in which `setup.py` file is. 

So, make the changes in 
https://github.com/abhinavsp0730/khronos/blob/a9f09e6a81c89808452917325ded0aff78bb39ab/Khronos/setup.py#L7
in way it'll open the  `README.md` file from root dir.

### PR DESCRIPTION
**Pull request by Paul-Annay**
## What changes does this PR introduce?

A single line of code is added 
```python 
os.chdir('../')
``` 
This changes the **current directory** to **parent**, therefore, making the README.md file accessible while preserving the current files execution.

Fix #5

### CODE REVIEW

**Comment by abhinavsp0730** [comment]
Hey, would you please run `python -m build` and upload the package using twine to test pypi?
And see if the long description is rendering correctly?

**Comment by Paul-Annay** [comment]
Okay on it!

**Comment by abhinavsp0730** [comment]
Make sure you upload it to testPyPi and not the actual PyPi.
https://packaging.python.org/en/latest/guides/using-testpypi/

**Comment by Paul-Annay** [comment]
Yes, I have uploaded to the testPyPi package manager. Apparently I am having trouble in figuring out how to check whether the `long_description` is rendering correctly. Do I have to create a django-project and install django-khronos in order to execute any commands from the CLI?

**Comment by Paul-Annay** [comment]
long-description-correctly-rendered

Executing the command from the terminal shows the expected results

**Comment by Paul-Annay** [comment]
I have made slight modification to the code by replacing the `open` function with the `with` context manager and used raw file path instead of importing the `os` module.

**Comment by abhinavsp0730** [comment]
> Yes, I have uploaded to the testPyPi package manager. Apparently I am having trouble in figuring out how to check whether the `long_description` is rendering correctly. Do I have to create a django-project and install django-khronos in order to execute any commands from the CLI?

Can you send me the link?

**Comment by Paul-Annay** [comment]
Yeah, sure [link](https://test.pypi.org/project/django-khronos/)

**Comment by abhinavsp0730** [comment]
> Yeah, sure [link](https://test.pypi.org/project/django-khronos/)

Any idea why  the text is not properly formatted?
```
â€¨Feautres:
â€¨1) Benchmark Report: Create benchmark report in the terminal whenever you run your django tests and shows top 10(this no. can be configured) slowest tests.â€¨
2) Parallel Test Execution: Works with --parallel out of the box.
â€¨3) Google Sheets Integration: Whole tests benchmark can be automatically uploaded to Google Sheets.â€¨
4) CSV Export: Whole tests benchmark can be saved in a CSV.
```  

 See here https://pypi.org/project/django-khronos/ it's properly formatted?

**Comment by Paul-Annay** [comment]
@abhinavsp0730 No I am a bit clue-less myself.

**Comment by abhinavsp0730** [comment]
Okay gonna merge anyway.  
Thanks for the contribution.

**Pull request merged**
